[package]
name = "cereus"
version = "0.1.0"
authors = ["CactusDev"]

[dependencies]
ws = { version = "*", git = "https://github.com/housleyjk/ws-rs"}
env_logger = "0.4.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
