[package]
name = "cereus_commands"
version = "0.1.0"
authors = ["Innectic <innectic@gmail.com>"]
edition = "2018"

[dependencies]
cereus_core = { path = "../cereus_core" }
reqwest = "0.9.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
regex = "1"
rand = "0.6.0-pre.0"
